### ISSUE TITLE
Doesn't depend on logrus

### ISSUE THREAD

**Issue by cjones-vultr** [YuKitsune/lokirus#5]
This package doesn't actually require logrus which seems really strange.  Is it possible to use it without logrus?

**Comment by YuKitsune** [comment]
Hey @cjones-vultr. This package does depend on logrus. The hook needs to adhere to the interface that logrus expects, which includes accepting a `logrus.Entry` type. It's also required to translate log levels into something that Loki can understand.

https://github.com/YuKitsune/lokirus/blob/7ec028ab8e16d8ca879e5929b69b9dd11b0f414a/logrusloki.go#L45

**Comment by cjones-vultr** [comment]
Boy do I have egg on my face.  I'd swear I looked in the go.mod file yesterday and didn't see logrus but I guess I just missed it.  I'm sorry for the erroneous issue.
